# if (!require("trajeR")) devtools::install_github("gitedric/trajeR")
# library(trajeR)
# if (!require("tableone")) install.packages("tableone")
# library(tableone)

if (!require("haven")) install.packages("haven")
library(haven)
if (!require("tidyverse")) install.packages("tidyverse")
library(dplyr)
if (!require("lubridate")) install.packages("lubridate")
library(lubridate)
if (!require("data.table")) install.packages("data.table")
library(data.table)
if (!require("stringr")) install.packages("stringr")
library(stringr)
if (!require("purrr")) install.packages("purrr")
library(purrr)
if (!require("readr")) install.packages("readr")
library(readr)
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
if (!require("survival")) install.packages("survival")
library(survival)
if (!require("rmarkdown")) install.packages("rmarkdown")
library(rmarkdown )
if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2 )
if (!require("ggthemes")) install.packages("ggthemes")
library(ggthemes)
if (!require("plotly")) install.packages("plotly")
library(plotly)
if (!require("DT")) install.packages("DT")
library(DT)
if (!require("tableone")) install.packages("tableone")
library(tableone)
if (!require("officer")) install.packages("officer")
library(officer)
if (!require("flextable")) install.packages("flextable")
library(flextable)
if (!require("nnet")) install.packages("nnet")
library(nnet)
if (!require("png")) install.packages("png")
library(png)
